spring.datasource.url=jdbc:postgresql://localhost:5432/chopar_test
spring.datasource.username=task_test
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#=======================
#   SERVER
#======================

server.url=http://localhost:8080
server.port=8080