spring:
   application:
       name: fie-service
   datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mydb}
     username: ${DB_USERNAME:myuser}
     password: ${DB_PASSWORD:12345}
   jpa:
     hibernate:
       ddl-auto: none
   liquibase:
     enabled: true
     change-log: classpath:db/changelog/changelog-master.yml

minio:
     url: http://localhost:9000
     access-key: admin
     secret-key: admin123

server:
  port: 5555
